### ISSUE TITLE
"Review cannot be requested from pull request author." error thrown when a default reviewer opens a PR.

### ISSUE THREAD

**Issue by A-Tokyo** [necojackarc/auto-request-review#31] opened 2021-02-11 12:54 UTC
When the PR author is assigned as a default reviewer, the action fails with the error "Review cannot be requested from pull request author." .

Expected behavior:
Simply skip the reviewer addition if the reviewer is the same as the PR author.

**Comment by necojackarc** [comment] 2021-02-13 03:17
@A-Tokyo Thanks for reporting a bug!

Could you share your settings and the author name when you saw the error? I can't seem to reproduce the bug and actually, there is the logic to exclude the author from reviewers in the case you mentioned:

https://github.com/necojackarc/auto-request-review/blob/de08bc01df159d14edcac92205cc92082c6982ff/src/index.js#L53

The logic does just a simple comparison, so I wonder whether or not there might be a case-sensitivity issue in your settings.

**Comment by A-Tokyo** [comment] 2021-02-15 10:12
@necojackarc Thanks for the response!

I don't have the code atm as I replaced it with another library, but I know for a fact that my username sometimes has case sensitivity issues. It's actually `A-tokyo`. So it might be that.

The Logic I did was to assign `a-tokyo` and `qa-team` as default reviewers. `a-tokyo` is in the QA team as well.


Feel free to either try it out or close the issue  = )

**Comment by necojackarc** [comment] 2021-02-17 18:50
@A-Tokyo Thanks. Yeah, it sounds like an issue around case sensitivity. I believe it could work if you used exactly the same username in the settings 👍 

I'm happy to leave this issue open as this sounds like a common issue for those who use any capital letters in their usernames. I hope I can find some time and compare the names in a case-insensitive way.

**Comment by necojackarc** [comment] 2021-02-23 19:13
It turns out this isn't a bug, so I'm closing this issue in order not to confuse us but I've added a new issue #37 to make it more convenient.

**Closed by necojackarc** 2021-02-23 19:13 UTC
Labels: bug, invalid
